language: php

php:
  - 5.6
  - 7.0

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y imagemagick
  - pecl install imagick
  - composer self-update
  - composer install --prefer-dist

script:
  - vendor/bin/phpcs -pn --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests